// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcWineAPP.Data;

namespace MvcWineAPP.Migrations.WineDB
{
    [DbContext(typeof(WineDBContext))]
    [Migration("20220223202008_update db")]
    partial class updatedb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcWineAPP.Models.Grape", b =>
                {
                    b.Property<int>("GrapeID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("RedGrape")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhiteGrape")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GrapeID");

                    b.ToTable("Grape");
                });

            modelBuilder.Entity("MvcWineAPP.Models.Wine", b =>
                {
                    b.Property<int>("WineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PairsWith")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WineVintage")
                        .HasColumnType("int");

                    b.HasKey("WineID");

                    b.ToTable("Wine");
                });

            modelBuilder.Entity("MvcWineAPP.Models.WineType", b =>
                {
                    b.Property<int>("WineTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int?>("GrapeID")
                        .HasColumnType("int");

                    b.Property<int>("GrapesID")
                        .HasColumnType("int");

                    b.Property<int>("WineID")
                        .HasColumnType("int");

                    b.HasKey("WineTypeID");

                    b.HasIndex("GrapeID");

                    b.HasIndex("WineID");

                    b.ToTable("WineType");
                });

            modelBuilder.Entity("MvcWineAPP.Models.WineType", b =>
                {
                    b.HasOne("MvcWineAPP.Models.Grape", "Grape")
                        .WithMany()
                        .HasForeignKey("GrapeID");

                    b.HasOne("MvcWineAPP.Models.Wine", "Wine")
                        .WithMany()
                        .HasForeignKey("WineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grape");

                    b.Navigation("Wine");
                });
#pragma warning restore 612, 618
        }
    }
}
